### PR TITLE
fix: Resolve TS 3.7 errors

### PR DESCRIPTION
**Pull request by ffflorian**
When building `reconnecting-websocket` with TypeScript 3.7, there were two errors:

```
[!] (rpt2 plugin) Error: /[redacted]/reconnecting-websocket/reconnecting-websocket.ts(8,5):
semantic error TS2440: Import declaration conflicts with local declaration of 'CloseEvent'.
```

```
[!] (rpt2 plugin) Error: /[redacted]/reconnecting-websocket/reconnecting-websocket.ts(336,17):
semantic error TS2774: This condition will always return true since the function is always defined. Did you mean to call it instead?
```

Both of them appeared also when using the definition files in another project with TypeScript 3.7 breaking it's build.

This fixes both of them and re-building the project will create a 3.7-compatible `.d.ts` file.

### CODE REVIEW

**Comment by EricCrosson** [comment]
On my machine this branch fails to pass the provided tests

**Comment by ffflorian** [comment]
@EricCrosson thanks for the hint, I didn't notice that. It's fixed now and @pladaria can decide which PR to accept :)

**Comment by EricCrosson** [comment]
quick on the draw @ffflorian , nice work 👍

**Comment by bennyn** [comment]
@pladaria Have you had time to look into it?

**Comment by bennyn** [comment]
@pladaria Do you need support for your library?

**Comment by bennyn** [comment]
@pladaria We forked your library to make it work with TypeScript 3.7:
https://github.com/wireapp/reconnecting-websocket/tree/fix-types

If anyone wants to benefit from the PR here, then please add the following to your `package.json`:

```
"reconnecting-websocket": "wireapp/reconnecting-websocket#96ac796ae8c7a7d9d857f46ed39dbedd7b9ad378"
```

**Comment by bennyn** [comment]
@pladaria Are you reading this?

**Comment by bennyn** [comment]
@pladaria I am back from Christmas holidays. How about you? 🎄

**Comment by quentinus95** [comment]
Would someone be ready and have time to create, publish and maintain a separate fork of this lib? Most pull requests take about a year to be merged (for simple fixes), e.g. https://github.com/pladaria/reconnecting-websocket/pull/94. I believe it could be useful to create and maintain a separate repository.

**Comment by pladaria** [comment]
Thanks!

**Comment by pladaria** [comment]
published reconnecting-websocket@4.3.0
